import dotenv from "dotenv";
dotenv.config();

const { PORT, DB_URL, NODE_ENV, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET, INNGEST_SIGNING_KEY } = process.env;

export { PORT, DB_URL, NODE_ENV, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET,INNGEST_SIGNING_KEY };
